version: '3.1'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_api_dev
    ports:
      - '5432:5432'
